# Generated by Django 5.2.9 on 2026-01-03 00:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del proyecto', null=True, upload_to='imagenes_proyectos/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sede', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('staff', 'Personal'), ('user', 'Usuario/Atleta')], default='user', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('departamento', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='Foto del atleta', null=True, upload_to='imagenes_perfil/')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('comentario_general', models.TextField(blank=True, null=True)),
                ('comentario_academico', models.TextField(blank=True, null=True)),
                ('comentario_economico', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario en Proyecto',
                'verbose_name_plural': 'Usuarios en Proyectos',
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(related_name='proyectos_participando', through='api.ProyectoUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=150)),
                ('ano_academico', models.CharField(max_length=4)),
                ('adecuacion', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo_adecuacion', models.CharField(blank=True, max_length=80, null=True)),
                ('tiene_beca', models.BooleanField(default=False)),
                ('monto_beca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('institucion_beca', models.CharField(blank=True, max_length=80, null=True)),
                ('adjunto_notas', models.FileField(blank=True, help_text='Subir notas (PDF o imagen)', null=True, upload_to='adjuntos_notas/')),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('telefono_principal', models.CharField(max_length=30)),
                ('telefono_secundario', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(verbose_name='Lugar de residencia')),
                ('lesiones', models.TextField(blank=True, help_text='Historial de lesiones del atleta', null=True)),
                ('enfermedades', models.TextField(blank=True, help_text='Enfermedades o condiciones médicas', null=True)),
                ('tratamientos', models.TextField(blank=True, help_text='Tratamientos médicos actuales', null=True)),
                ('atencion_medica', models.TextField(blank=True, help_text='Centro de atención médica y doctor', null=True)),
                ('drogas', models.CharField(blank=True, help_text='Consumo de sustancias', max_length=200, null=True)),
                ('disponibilidad', models.TextField(blank=True, help_text='Disponibilidad para entrenamientos y competencias', null=True)),
                ('tipo_vivienda', models.CharField(choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('prestada', 'Prestada'), ('otro', 'Otro')], max_length=20)),
                ('monto_vivienda', models.DecimalField(decimal_places=2, default=0, help_text='Monto de alquiler o hipoteca', max_digits=10)),
                ('especificaciones_vivienda', models.TextField(blank=True, null=True)),
                ('trabaja', models.BooleanField(default=False)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comentario_empleo', models.TextField(blank=True, null=True)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_agua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_luz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_internet_cable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_celular', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deudas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_visita', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.expediente')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('parentesco', models.CharField(help_text='Ej: Padre, Madre, Hermano, Tío, etc.', max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=400, null=True)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=400, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='api.visita')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
    ]
